// <auto-generated />
namespace videoprokat_winform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pricepropertiesinmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pricepropertiesinmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202011190634272_price properties in models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
