// <auto-generated />
namespace videoprokat_winform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class flavormodelspropertieschanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flavormodelspropertieschanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202011190652456_flavor models properties changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
