// <auto-generated />
namespace videoprokat_winform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removedclientLeaseCopymethodasitisuseless : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedclientLeaseCopymethodasitisuseless));
        
        string IMigrationMetadata.Id
        {
            get { return "202011200503372_removed client LeaseCopy method as it is useless"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
