// <auto-generated />
namespace videoprokat_winform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class razborkisdatetimomvleasing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(razborkisdatetimomvleasing));
        
        string IMigrationMetadata.Id
        {
            get { return "202011190904440_razborki s datetimom v leasing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
